export const SHIPS = [
 {id:'bastion',name:'Bastion Battleship',cost:14,minLevel:5,maxCopies:1,cells:[[0,0],[0,1],[0,2],[1,2],[2,2]],armor:{2:3},ability:'broadside',abilityName:'Broadside',uses:1,description:'Corner has 3 health. Once: attack three consecutive cells in a row or column.'},
 {id:'kestrel',name:'Kestrel Light Carrier',cost:15,minLevel:5,maxCopies:1,cells:[[0,0],[1,0],[0,1],[1,1],[0,2],[1,2]],ability:'scan',abilityName:'Reconnaissance Flight',uses:2,planeCount:2,scanSize:3,description:'Two deck planes, each scanning a 3×3 area. A hit destroys a plane on that section.'},
 {id:'atlas',name:'Atlas Fleet Carrier',cost:20,minLevel:7,maxCopies:1,cells:[[0,0],[1,0],[2,0],[3,0],[4,0],[2,1],[2,2]],ability:'scan',abilityName:'Reconnaissance Flight',uses:3,planeCount:3,scanSize:4,gap:true,description:'Three deck planes scan 4×4 areas. Keep a one-cell gap from other ships, including diagonally.'},
 {id:'lantern',name:'Lantern Support Ship',cost:12,minLevel:4,maxCopies:1,cells:[[1,0],[0,1],[1,1],[2,1],[1,2]],ability:'fieldRepair',abilityName:'Field Repair',uses:2,description:'Twice: restore 1 health to another surviving friendly ship. Uses support supply rather than its onboard repairs.'},
 {id:'moray',name:'Moray Attack Submarine',cost:12,minLevel:5,maxCopies:1,cells:[[0,0],[0,1],[0,2],[1,2]],submarine:true,ability:'torpedo',abilityName:'Torpedo Spread',uses:1,description:'Hidden from radar and aircraft. Once: attack three consecutive cells in a row or column. No armor.'},
 {id:'breakwater',name:'Breakwater Arsenal Ship',cost:19,minLevel:6,maxCopies:1,cells:[[0,0],[2,0],[0,1],[2,1],[0,2],[1,2],[2,2]],armor:{4:2,6:2},gap:true,ability:'saturation',abilityName:'Saturation Fire',uses:1,description:'Once: attack a 2×2 area. Lower corners have 2 health. Keep a one-cell gap from other ships, including diagonally.'},
 {id:'needle',name:'Needle Patrol Boat',cost:4,minLevel:1,cells:[[0,0],[1,0]],description:'Compact two-cell scout. Multiple may form a screen.',ability:null,uses:0},
 {id:'mako',abilityName:'Depth Charge',name:'Mako Destroyer',cost:7,maxCopies:3,minLevel:1,cells:[[0,0],[1,0],[2,0]],description:'One 3×3 depth charge. Damages submarines only.',ability:'depth',uses:1},
 {id:'wraith',abilityName:'Hydrophone',name:'Wraith Submarine',cost:8,maxCopies:1,minLevel:2,cells:[[0,0],[1,0],[2,0]],description:'Hidden from radar and aircraft. Hydrophone counts submarine cells in a row.',ability:'hydrophone',uses:1,submarine:true},
 {id:'echo',abilityName:'Sonar Pulse',name:'Echo Sonar Corvette',cost:8,maxCopies:3,minLevel:1,cells:[[0,0],[1,0],[0,1]],description:'Two sonar pulses. Reveals a submarine cell; excludes ships and mines.',ability:'sonar',uses:2},
 {id:'beacon',abilityName:'Active Radar',name:'Beacon Radar Cutter',cost:9,maxCopies:1,minLevel:2,cells:[[0,0],[1,0],[2,0]],description:'One radar pulse reveals a surface-ship cell or a deceptive mine.',ability:'radar',uses:1},
 {id:'bulwark',name:'Bulwark Cruiser',cost:10,maxCopies:1,minLevel:3,cells:[[0,0],[1,0],[2,0],[3,0]],description:'Middle sections have two health each. Two repairs.',ability:null,uses:0,armor:{1:2,2:2}},
 {id:'trident',abilityName:'Paired Fire',name:'Trident Frigate',cost:10,maxCopies:1,minLevel:3,cells:[[0,0],[1,0],[2,0],[1,1]],description:'Once per battle, attack two orthogonally adjacent cells in a row or column.',ability:'paired',uses:1},
 {id:'osprey',abilityName:'Reconnaissance Flight',name:'Osprey Seaplane Tender',cost:10,maxCopies:1,minLevel:4,cells:[[0,0],[1,0],[2,0],[2,1]],description:'Carries one plane. Place it on a hull section during deployment; a hit destroys the plane and its flight.',ability:'scan',uses:1,scanSize:3,planeCount:1}
];
export const CAPTAINS = [
 {id:'mercer',name:'Ada Mercer',cost:4,minLevel:4,abilityName:'Quiet Hands',ability:'quietRepair',trigger:'Active',description:'Once: restore 1 health to her ship. All repairs performed by her ship are silent.'},
 {id:'graves',name:'Leonie Graves',cost:4,minLevel:3,abilityName:'Signal Officer',ability:'captainRadar',trigger:'Active',description:'Once: spend an action to reveal a surface section or mine using radar. Submarines are excluded.'},
 {id:'park',name:'Jun Park',cost:3,minLevel:5,abilityName:'Wide Sweep',ability:'wideScan',trigger:'Active',aircraftOnly:true,description:'Carriers only. Once: launch a plane with scan width and height increased by one. Does not add a plane.'},
 {id:'flint',name:'Petra Flint',cost:3,minLevel:4,abilityName:'Armor Piercer',ability:'piercing',trigger:'Active',description:'Once: fire a normal shot dealing 2 damage to one cell. Excess damage does not spread.'},
 {id:'shaw',name:'Owen Shaw',cost:3,minLevel:3,abilityName:'Black Box',trigger:'On sinking',description:'When sunk, immediately receive one radar contact. No action or free shot.'},
 {id:'ward',abilityName:'Reinforce',trigger:'Passive',name:'Elias Ward',cost:3,minLevel:1,description:'First hull section gains one maximum health.'},
 {id:'rook',abilityName:'Damage Control',trigger:'Passive',name:'Tomas Rook',cost:3,minLevel:1,description:'One additional onboard repair.'},
 {id:'pike',abilityName:'Bloodhound',trigger:'On hit',name:'Soren Pike',cost:4,minLevel:3,description:'Once: a normal ship hit grants an adjacent bonus shot.'},
 {id:'ortiz',abilityName:'Mine Hunter',trigger:'Before firing',name:'Rafael Ortiz',cost:2,minLevel:2,description:'First two normal shots inspect for mines. Clearing a mine allows a replacement shot.'},
 {id:'voss',abilityName:'Last Word',trigger:'On sinking',name:'Mara Voss',cost:4,minLevel:4,description:'When sunk, immediately fire three retaliation shots.'}
];
